server:
  port: 8001
spring:
  datasource:
    url: jdbc:mysql://192.168.11.128/design_pattens?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: root
    password: "root"
    driver-class-name: com.mysql.jdbc.Driver